### ISSUE TITLE
Percheron needs a logo

### ISSUE THREAD

**Issue by clouseauu** [ashmckenzie/percheron#1]
Yeah, that. Assign to me  :sunglasses:

**Comment by ashmckenzie** [comment]
Aha!  It doesn't seem to let me assign to you?  Weird..

**Comment by ashmckenzie** [comment]
brilliant!  ![logo](https://github.com/ashmckenzie/percheron/raw/master/percheron-logo.png)

**Comment by 90kts** [comment]
:+1:

**Comment by nadnerb** [comment]
That is awesome !! top work @clouseauu.
